### ISSUE TITLE
Problem with docs in ReductionSystem

### ISSUE THREAD

**Issue by fmontesi** [cs-lean/cslib#20]
The docs are not building, citing a problem in ReductionSystem:

https://github.com/cs-lean/cs-lean.github.io/actions/runs/16546099688/job/46793949919#step:5:1178

**Comment by chenson2018** [comment]
Okay, a couple of things here. Note that the issue appears in both `ReductionSystem` and `LTS`, in the same parts of the elaborators for our reduction attributes.  The issue stems from our library and the docs directory being on different toolchains (this happened in https://github.com/cs-lean/cslib/commit/957359ab0cf16df126ed6e3d7861c868ef001477). This is maybe a nice check to add to our workflows, it could be as simple as a step with:
```bash
set -e
cmp -s lean-toolchain docs/lean-toolchain
```

First, I tried updating the docs toolchain, but ran into some failures from doc-gen4. In the meantime we could resolve the issue by a small change that works between toolchains. There was also another error regarding some typeclasses not being marked as `noncomputable`. These are both addressed in #21.

Could you help me understand the setup you have here for the documentation workflow? I would find it preferable that this happens in `.github/workflows/lean_action_ci.yml` on merging into main for discoverability when there is an issue like this.

**Comment by fmontesi** [comment]
Good find, thanks! We should certainly check that the toolchains are in sync, so I've added the commands you suggest.

Re the docs workflow: building the docs takes a pretty long time, so I made it a cron job that runs regularly (currently every 12 hours). You can find the action here: https://github.com/cs-lean/cs-lean.github.io/blob/main/.github/workflows/update-cslib-docs.yaml

**Comment by fmontesi** [comment]
Still failing, but for other reasons. Maybe we need to version bump some dependencies?

https://github.com/cs-lean/cs-lean.github.io/actions/runs/16551953783/job/46808105870#step:5:76

**Comment by fmontesi** [comment]
Alright, I've figured it out. :-)

The steps we gotta do every time are:
- Make sure that the Lean toolchains in root and `docs` are the same.
- Make sure that docgen4 has the right version in `docs/lakefile.toml`.
- Run `MATHLIB_NO_CACHE_ON_UPDATE=1 lake update doc-gen4` in `docs`.
